export const currency = '$'
export const currentYear = new Date().getFullYear()
export const developedByLink = 'https://atrch.com/'
export const developedBy = 'Appsido'
export const contactUs = 'atrchstudio@gmail.com'
export const buyLink = ''
export const basePath = ''
export const DEFAULT_PAGE_TITLE = 'Atrch | Responsive Admin Dashboard'
export const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'purple', 'pink', 'orange', 'light', 'link']
